
			SELECT B.MTR_DATE AS STAND_DT
				, B.TIME_CD, SUM(B.ECURR_EXCS_CNT) AS ECURR_EXCS_CNT
				, SUM(B.VOLT_EXCS_CNT) AS VOLT_EXCS_CNT
				, SUM(B.FRQN_EXCS_CNT) AS FRQN_EXCS_CNT
				, SUM(B.VOLT_BLOW_CNT) AS VOLT_BLOW_CNT
				, SUM(B.POWER_FACTR_AVG) AS POWER_FACTR_AVG
				, SUM(B.FRQN_AVG) AS FRQN_AVG
				FROM T_OBDNG_INFO_BAS A, T_OBDNG_BY_PURP_MN15_SUM B
			WHERE A.OBDNG_ID = B.OBDNG_ID
				AND A.RGN_CD = '01020000'
			AND B.MTR_DATE BETWEEN '20131022' AND '20131023'
			GROUP BY B.MTR_DATE, B.TIME_CD


			SELECT  i, to_char('20131024'::date - i,'yyyymmdd') as STAND_DT, START_TM, END_TM, TIME_CD
			FROM generate_series(0,(select '20131024'::date - '20131024'::date)) as t(i) 
			INNER JOIN T_TIME_CD 
			ON CD_TYPE='M15'
			ORDER BY STAND_DT, START_TM