SELECT *
FROM T_obdng_info_tmp;

SELECT MANDT
			, JOBDATE
			, BUKRS
			, AOID
			, ORGEH2
			, SEQ
			, INTRENO
			, OBJNR
			, ZRECN_DIV2
			, ORGTX
			, AONR
			, XAO
			, ZBIMMANAGED
			, ZBUPJUNGDONG
			, ZBUPJUNGDONGTXT
			, A001
			, A002
			, A003
			, MEASUNIT
			, Z04FL
			, Z05RM
			, Z05RMXAO
			, Z05RMXDEL
			, AOFUNCTION
			, XSAOFUNCTION
			, RECNNR
			, B006
			, ZSPACE_NAME
			, ZSPACE_NAMETX
			, ZSPACE_TYPE
			, ZSPACE_TYPETX
			, ZROOM_TYPE
			, ZROOM_TYPETX
			, ZAREA_TYPE
			, ZAREA_TYPE
			, ZSPACE_USAGE
			, ZSPACE_USAGETX
			, ZSPACE_USAGE2
			, ZSPACE_USAGE2TX
			, Z_ORG_CD
			, Z_ORG_NM
			, Z_RATE
			, VALIDFROM
			, VALIDTO
			, STATUS_TX
			, CRET_DT
		FROM T_OBDNG_INFO_TMP;

		SELECT *
		FROM T_OBDNG_INFO_BAS

		INSERT INTO T_obdng_info_tmp
			(AOID
			, ORGTX
			, ZBUPJUNGDONG
			, ZBUPJUNGDONGTXT
			, A001
			, Z04FL
			, B006
			, Z05RM
			, Z05RMXAO
			, ZROOM_TYPE
			, CRET_DT)
		SELECT A.AOID
			, A.ORGTX
			, A.ZBUPJUNGDONG
			, A.ZBUPJUNGDONGTXT
			, A.A001
			, A.Z04FL
			, A.B006
			, B.OFCE_ID AS Z05RM
			, B.OFCE_NM AS Z05RMXAO
			, B.INSTN_ID AS ZROOM_TYPE
			, B.AREA_VAL AS B006
			, B.OFCE_NM AS Z05RMXAO
			, CURRENT_TIMESTAMP
		FROM (
			SELECT A.OBDNG_ID AS AOID
				, A.OBDNG_NM AS ORGTX
				, A.TOWN_CD AS ZBUPJUNGDONG
				, A.OBDNG_ADR AS ZBUPJUNGDONGTXT
				, A.GRS_VAL AS A001
				, B.FLR_ID AS Z04FL
			FROM T_OBDNG_INFO_BAS A RIGHT JOIN T_OBDNG_FLR_INFO_BAS B
			ON A.OBDNG_ID = B.OBDNG_ID
		) A RIGHT JOIN T_OBDNG_INSTN_INFO_BAS B
		ON A.AOID = B.OBDNG_ID
		AND A.Z04FL = B.FLR_ID

		

		SELECT COUNT(*)
		FROM T_OBDNG_INFO_BAS A, T_OBDNG_FLR_INFO_BAS B
		WHERE A.OBDNG_ID = B.OBDNG_ID
		

SELECT A.AOID
	, A.ORGTX
	, A.ZBUPJUNGDONG
	, A.ZBUPJUNGDONGTXT
	, A.A001
	, A.Z04FL
	, A.B006
	, B.OFCE_ID AS Z05RM
	, B.OFCE_NM AS Z05RMXAO
	, B.INSTN_ID AS ZROOM_TYPE
	, B.AREA_VAL AS B006
	, B.OFCE_NM AS Z05RMXAO
FROM (
	SELECT A.OBDNG_ID AS AOID
		, A.OBDNG_NM AS ORGTX
		, A.TOWN_CD AS ZBUPJUNGDONG
		, A.OBDNG_ADR AS ZBUPJUNGDONGTXT
		, A.GRS_VAL AS A001
		, B.FLR_ID AS Z04FL
		, B.FLR_AREA_VAL AS B006
	FROM T_OBDNG_INFO_BAS A RIGHT JOIN T_OBDNG_FLR_INFO_BAS B
	ON A.OBDNG_ID = B.OBDNG_ID
) A RIGHT JOIN T_OBDNG_INSTN_INFO_BAS B
ON A.AOID = B.OBDNG_ID
AND A.Z04FL = B.FLR_ID

SELECT *
FROM T_OBDNG_INFO_BAS
LIMIT 1




		INSERT INTO T_obdng_info_tmp
			(AOID
			, ORGTX
			, ZBUPJUNGDONG
			, ZBUPJUNGDONGTXT
			, A001
			, Z04FL
			, B006
			, Z05RM
			, Z05RMXAO
			, ZROOM_TYPE
			, CRET_DT)
		SELECT A.AOID
			, A.ORGTX
			, A.ZBUPJUNGDONG
			, A.ZBUPJUNGDONGTXT
			, A.A001
			, A.Z04FL
			, B.OFCE_ID AS Z05RM
			, B.OFCE_NM AS Z05RMXAO
			, B.INSTN_ID AS ZROOM_TYPE
			, B.AREA_VAL AS B006
			, B.OFCE_NM AS Z05RMXAO
			, CURRENT_TIMESTAMP
		FROM (
			SELECT A.OBDNG_ID AS AOID
				, A.OBDNG_NM AS ORGTX
				, A.TOWN_CD AS ZBUPJUNGDONG
				, A.OBDNG_ADR AS ZBUPJUNGDONGTXT
				, A.GRS_VAL AS A001
				, B.FLR_ID AS Z04FL
			FROM T_OBDNG_INFO_BAS A RIGHT JOIN T_OBDNG_FLR_INFO_BAS B
			ON A.OBDNG_ID = B.OBDNG_ID
		) A RIGHT JOIN T_OBDNG_INSTN_INFO_BAS B
		ON A.AOID = B.OBDNG_ID
		AND A.Z04FL = B.FLR_ID