SELECT *
FROM T_OBDNG_BY_PURP_BYTM_SUM

SELECT POWER_FACTR_AVG, FRQN_AVG
FROM T_OBDNG_INFO_BAS A, T_OBDNG_BY_PURP_MN15_SUM B
WHERE A.OBDNG_ID = B.OBDNG_ID
  AND MTR_DATE = '20131021'
ORDER BY TIME_CD DESC
LIMIT 1

SELECT A.PF_VAL, A.FRQN_MAX, B.PF_VAL, B.FRQN_MAX
FROM(
SELECT PF_VAL, FRQN_MAX
FROM T_QUALITY_FACTOR
WHERE USE_YN = 'Y'
ORDER BY SEQ DESC
LIMIT 1) A,
(SELECT PF_VAL, FRQN_MAX
FROM T_QUALITY_FACTOR
WHERE USE_YN = 'Y'
ORDER BY SEQ DESC
LIMIT 1) B



-- UPDATE T_QUALITY_FACTOR
-- SET PF_VAL = 0.9,
-- 	FRQN_MAX = 60
-- WHERE SEQ = '10000182'

-- COMMIT;

SELECT AVG(POWER_FACTR_AVG) AS POWER_FACTR_AVG, AVG(FRQN_AVG) AS FRQN_AVG
FROM T_OBDNG_INFO_BAS A, T_OBDNG_BY_PURP_BYTM_SUM B
WHERE A.OBDNG_ID = B.OBDNG_ID
AND MTR_DATE = '20131017'

SELECT SUBSTR('20131017', 0, 7)

SELECT COALESCE(PF_VAL, 0)
						FROM T_QUALITY_FACTOR
						WHERE USE_YN = 'Y'
						ORDER BY SEQ DESC
						LIMIT 1