SELECT *
FROM T_MR_METER_MBY_SUM

SELECT *
FROM T_MR_METER_BYTM_SUM

SELECT *
FROM T_OBDNG_INFO_BAS

SELECT C.OBDNG_REP_ID, B.ISMART_ID, C.ASGN_RATE, C.IP_SET, B.LATIT, C.LNGIT, B.RGN_CD, B.OBDNG_ADR, B.CHAGE_APLY_ELECT, B.CONT_ELECT
		FROM T_OBDNG_BAS B, T_OBDNG_IF_BAS C
		WHERE B.OBDNG_REP_ID = C.OBDNG_REP_ID


select *
from T_OBDNG_FLR_BYTM_SUM		


select ref2 as m_time_cd , time_cd   from t_time_cd where cd_type = 'M15' 

SELECT *
FROM T_GROUP_CBL
WHERE CBL IS NOT NULL

			SELECT B.STAND_DT
				, B.TIME_CD
				, B.START_TM
				, B.END_TM
				, COALESCE(A.CBL, 0) AS CBL
			FROM (
				SELECT A.STAND_DT
					, A.TIME_CD 
					, SUM(A.CBL) AS CBL
				FROM T_GROUP_CBL A, T_OBDNG_INFO_BAS B
				WHERE A.GROUP_CD = B.OBDNG_ID
				  AND B.RGN_CD = '01020000'
				  AND A.STAND_DT BETWEEN '20131020' AND '20131020'
				GROUP BY A.STAND_DT, A.TIME_CD, A.CBL
			) A RIGHT JOIN (
					SELECT  i, to_char('20131022'::date - i,'yyyymmdd') as STAND_DT, START_TM, END_TM, TIME_CD
					FROM generate_series(0,(select '20131020'::date - '20131020'::date)) as t(i) 
					INNER JOIN T_TIME_CD 
					ON CD_TYPE='H01'
					ORDER BY STAND_DT, START_TM
			) B
			ON A.TIME_CD = B.TIME_CD
			AND A.STAND_DT = B.STAND_DT

			--m_time_cd

			select *
			from t_region_cd
			where region_cd = '01000000'

			SELECT COUNT(*)
			FROM T_OBDNG_INFO_BAS A, T_REGION_CD B
			WHERE A.RGN_CD = B.REGION_SUB_CD


SELECT *
FROM T_REGION_CD C
WHERE C.REGION_CD = ''
			
SELECT *
FROM T_OBDNG_INFO_BAS
where 

			SELECT A.STAND_DT
					, C.REF2 AS m_time_cd
					, SUM(A.CBL) AS CBL
					, b.obdng_id
				FROM T_GROUP_CBL A, T_OBDNG_INFO_BAS B, T_TIME_CD C
				WHERE A.GROUP_CD = B.OBDNG_ID
				  AND A.TIME_CD = C.TIME_CD
				  --AND B.RGN_CD = '01020000'
				  and b.obdng_id = 'A01-B0000000896'
				  AND A.STAND_DT BETWEEN '20131020' AND '20131020'
				GROUP BY A.STAND_DT, C.REF2, b.obdng_id





				SELECT A.STAND_DT
					, SUM(A.CBL) AS CBL
				FROM T_GROUP_CBL A, T_OBDNG_INFO_BAS B
				WHERE A.GROUP_CD = B.OBDNG_ID
				  AND A.STAND_DT BETWEEN '20131020' AND '20131020'
				  AND B.RGN_CD ='A01-B0000000871'
				GROUP BY A.STAND_DT


		select *
		from t_obdng_info_bas
		where obdng_id = 'A01-B0000000896'









				SELECT  A.REGION_CD, A.REGION_SUB_CD, A.REGION_SUB_CD_V2, A.REGION_NM, A.LVL, A.SCALE, A.VIEW_ODR, A.USE_YN, A.COMMENT, A.REG_DATE
		FROM (
			SELECT REGION_CD, REGION_SUB_CD, REGION_SUB_CD AS REGION_SUB_CD_V2, REGION_NM, LVL, SCALE, VIEW_ODR, USE_YN, COMMENT, REG_DATE
			FROM T_REGION_CD
			WHERE USE_YN = 'Y'
			UNION ALL
			SELECT A.REGION_SUB_CD AS REGION_CD, CONCAT(A.REGION_SUB_CD, '|', B.OBDNG_ID) AS REGION_SUB_CD, B.OBDNG_ID AS REGION_SUB_CD_V2, B.OBDNG_NM AS REGION_NM, '3' AS LVL, '12' AS SCALE, 20 AS VIEW_ODR, 'Y' AS USE_YN,
				COALESCE((SELECT OBDNG_ID AS SITE_ID FROM T_OBDNG_FLR_INFO_BAS C WHERE C.OBDNG_ID = B.OBDNG_ID GROUP BY C.OBDNG_ID), 'NODE_END') AS COMMENT, A.REG_DATE
			FROM T_REGION_CD A, T_OBDNG_INFO_BAS B
			WHERE A.REGION_SUB_CD = B.RGN_CD
			AND A.USE_YN = 'Y'
			UNION ALL
			SELECT C.REGION_SUB_CD AS REGION_CD, CONCAT(C.REGION_SUB_CD, '|', A.OBDNG_ID , '★', B.FLR_ID) AS REGION_SUB_CD, CONCAT(A.OBDNG_ID, '★', B.FLR_ID) AS REGION_SUB_CD_V2, CONCAT(A.OBDNG_NM, ' ', B.FLR_ID, '층') AS REGION_NM, '4' AS LVL , '17' AS SCALE, 25 AS VIEW_ODR, 'Y' AS USE_YN, 'NODE_END' AS COMMENT, B.CRET_DT AS REG_DATE
			FROM T_OBDNG_INFO_BAS A, T_OBDNG_FLR_INFO_BAS B, (
				SELECT B.OBDNG_ID AS REGION_CD, A.REGION_SUB_CD AS REGION_SUB_CD, B.OBDNG_NM AS REGION_NM, '3' AS LVL, '12' AS SCALE, 20 AS VIEW_ODR, 'Y' AS USE_YN, '' AS COMMENT
				FROM T_REGION_CD A, T_OBDNG_INFO_BAS B
				WHERE A.REGION_SUB_CD = B.RGN_CD
				  AND A.USE_YN = 'Y'
			) C
			WHERE A.OBDNG_ID = B.OBDNG_ID
			  AND A.RGN_CD = C.REGION_SUB_CD
			GROUP BY B.FLR_ID, A.OBDNG_ID, C.REGION_SUB_CD, B.CRET_DT
			ORDER BY REGION_SUB_CD, REGION_CD
		) A


				SELECT A.STAND_DT
					, C.REF2 AS TIME_CD 
					, SUM(A.CBL) AS CBL
				FROM T_GROUP_CBL A, T_OBDNG_INFO_BAS B, T_TIME_CD C
				WHERE A.GROUP_CD = B.OBDNG_ID
				  AND A.TIME_CD = C.TIME_CD
				  GROUP BY A.STAND_DT, C.REF2







				  SELECT A.MTR_DATE AS STAND_DT ,
				     A.TIME_CD ,
				     ROUND((CAST(SUM(A.RCV_NUM) AS NUMERIC)/CAST(SUM(A.BASE_COLEC_NUM) AS NUMERIC))*100, 1) AS MR_RATE ,
				     SUM(A.TOT_CNS_QNT) AS DEMAND
			      FROM T_OBDNG_BY_PURP_BYTM_SUM A ,
				   T_OBDNG_INFO_BAS B 
				   --T_REGION_CD C
			      WHERE A.OBDNG_ID = B.OBDNG_ID
				--AND B.RGN_CD = C.REGION_SUB_CD
				AND A.MTR_DATE BETWEEN '20131020' AND '20131020'
				--AND C.REGION_CD = '01000000'
			      GROUP BY A.MTR_DATE, A.TIME_CD


			      SELECT *
			      FROM T_OBDNG_INFO_BAS A, T_REGION_CD B
			      WHERE REGION_CD = '01000000'
			      AND A.RGN_CD = B.REGION_SUB_CD

			      DELETE FROM t_obdng_by_purp_dby_sum


SELECT *
FROM T_OBDNG_INFO_BAS


			      