			SELECT B.STAND_DT
				, B.TIME_CD
				, B.START_TM
				, B.END_TM
				, COALESCE(A.MR_RATE, 0) AS MR_RATE
				, COALESCE(A.DEMAND, 0) AS DEMAND
			FROM (
				SELECT A.MTR_DATE AS STAND_DT
					, A.TIME_CD
					, ROUND((CAST(SUM(A.RCV_NUM) AS NUMERIC)/CAST(SUM(A.BASE_COLEC_NUM) AS NUMERIC))*100, 1) AS MR_RATE
					, SUM(A.LGHTN_CCTP_CNS_QNT) AS DEMAND
					FROM T_OBDNG_FLR_BYTM_SUM A
					, T_OBDNG_FLR_INFO_BAS B
				WHERE A.OBDNG_ID = B.OBDNG_ID
					AND A.OBDNG_ID = 'A01-B0000000896'
					AND A.FLR_ID = '1'
				AND A.MTR_DATE BETWEEN '20131105' AND '20131105'
				GROUP BY A.MTR_DATE, A.TIME_CD
				) A RIGHT JOIN (
					SELECT  i, to_char('20131105'::date - i,'yyyymmdd') as STAND_DT, START_TM, END_TM, TIME_CD
					FROM generate_series(0,(select '20131105'::date - '20131105'::date)) as t(i) 
					INNER JOIN T_TIME_CD 
					ON CD_TYPE='H01'
					ORDER BY STAND_DT, START_TM
				) B
			ON A.STAND_DT = B.STAND_DT
			AND A.TIME_CD = B.TIME_CD
			ORDER BY A.STAND_DT, A.TIME_CD

			SELECT SUM(A.LGHTN_CCTP_CNS_QNT) AS DEMAND
			FROM T_OBDNG_FLR_BYTM_SUM A , T_OBDNG_FLR_INFO_BAS B
			WHERE A.OBDNG_ID = 'A01-B0000000896'
			    AND A.FLR_ID = '1'
			    AND A.MTR_DATE = '20131105'
			    AND A.OBDNG_ID  = B.OBDNG_ID
			    AND A.FLR_ID = B.FLR_ID
			GROUP BY A.MTR_DATE, A.TIME_CD
			ORDER BY A.TIME_CD