SELECT A,
       POWER_FACTR_AVG_NOW ,
       A.FRQN_AVG_NOW ,
       B.POWER_FACTR_AVG_DAY ,
       B.FRQN_AVG_DAY ,
       C.POWER_FACTR_AVG_MONTH ,
       C.FRQN_AVG_MONTH
FROM
  (SELECT COALESCE(POWER_FACTR_AVG, 0) AS POWER_FACTR_AVG_NOW ,
          COALESCE(FRQN_AVG, 0) AS FRQN_AVG_NOW
   FROM T_OBDNG_INFO_BAS A,
        T_OBDNG_BY_PURP_MN15_SUM B
   WHERE A.OBDNG_ID = B.OBDNG_ID
     AND A.RGN_CD = '01020000'
     AND B.MTR_DATE BETWEEN '20131016' AND '20131016'
   ORDER BY B.TIME_CD DESC LIMIT 1) A,
  (SELECT COALESCE(AVG(POWER_FACTR_AVG), 0) AS POWER_FACTR_AVG_DAY ,
          COALESCE(AVG(FRQN_AVG), 0) AS FRQN_AVG_DAY
   FROM T_OBDNG_INFO_BAS A,
        T_OBDNG_BY_PURP_DBY_SUM B
   WHERE A.OBDNG_ID = B.OBDNG_ID
     AND A.RGN_CD = '01020000'
     AND B.MTR_DATE BETWEEN '20131016' AND '20131016') B,
  (SELECT COALESCE(AVG(POWER_FACTR_AVG), 0) AS POWER_FACTR_AVG_MONTH ,
          COALESCE(AVG(FRQN_AVG), 0) AS FRQN_AVG_MONTH
   FROM T_OBDNG_INFO_BAS A,
        T_OBDNG_BY_PURP_MBY_SUM B
   WHERE A.OBDNG_ID = B.OBDNG_ID
     AND A.RGN_CD = '01020000'
     AND B.MTR_YM BETWEEN SUBSTR('20131016', 0, 7) AND SUBSTR('20131016', 0, 7)) C


     SELECT COALESCE(POWER_FACTR_AVG, 0) AS POWER_FACTR_AVG_NOW ,
          COALESCE(FRQN_AVG, 0) AS FRQN_AVG_NOW,
          b.*
   FROM T_OBDNG_INFO_BAS A,
        T_OBDNG_BY_PURP_MN15_SUM B
   WHERE A.OBDNG_ID = B.OBDNG_ID
     AND A.RGN_CD = '01020000'
     AND B.MTR_DATE BETWEEN '20131017' AND '20131017'
   ORDER BY B.TIME_CD DESC LIMIT 1

   SELECT *
   FROM T_OBDNG_BY_PURP_MN15_SUM
   WHERE MTR_DATE = '20131017'
     AND OBDNG_ID = 'A01-B0000000896'
   ORDER BY TIME_CD DESC
   

   UPDATE T_OBDNG_BY_PURP_MN15_SUM
   SET FRQN_AVG = '60'
   WHERE TIME_CD = 't096'
     AND OBDNG_ID = 'A01-B0000000896';
     
     COMMIT;

   