SELECT REGION_CD, REGION_SUB_CD, REGION_SUB_CD AS REGION_SUB_CD_V2, REGION_NM,  REGION_NM AS REGION_NM_V2, LVL, SCALE, VIEW_ODR, USE_YN,  
				CASE 	WHEN LVL='1' AND  (SELECT REGION_CD FROM T_REGION_CD WHERE REGION_SUB_CD=REGION_SUB_CD LIMIT 1) IS NULL THEN 'NODE_END'
				      	WHEN LVL='2' AND  (SELECT OBDNG_ID FROM T_OBDNG_INFO_BAS WHERE RGN_CD=REGION_SUB_CD LIMIT 1) IS NULL THEN 'NODE_END'
					ELSE ''
				END
		        AS COMMENT, REG_DATE
				FROM T_REGION_CD
				WHERE USE_YN = 'Y'
				UNION ALL
				SELECT A.REGION_SUB_CD AS REGION_CD, CONCAT(A.REGION_SUB_CD, '|', B.OBDNG_ID) AS REGION_SUB_CD, B.OBDNG_ID AS REGION_SUB_CD_V2, B.OBDNG_NM AS REGION_NM, B.OBDNG_NM AS REGION_NM_V2, '3' AS LVL, '12' AS SCALE, 20 AS VIEW_ODR, 'Y' AS USE_YN,
					COALESCE((SELECT OBDNG_ID AS SITE_ID FROM T_OBDNG_FLR_INFO_BAS C WHERE C.OBDNG_ID = B.OBDNG_ID GROUP BY C.OBDNG_ID), 'NODE_END') AS COMMENT, A.REG_DATE
				FROM T_REGION_CD A, T_OBDNG_INFO_BAS B
				WHERE A.REGION_SUB_CD = B.RGN_CD
				AND A.USE_YN = 'Y'
				UNION ALL
				SELECT C.REGION_SUB_CD AS REGION_CD, CONCAT(C.REGION_SUB_CD, '|', A.OBDNG_ID , '★', B.FLR_ID) AS REGION_SUB_CD, CONCAT(A.OBDNG_ID, '★', B.FLR_ID) AS REGION_SUB_CD_V2, CONCAT(A.OBDNG_NM, ' ', B.FLR_ID, '층') AS REGION_NM, CONCAT(B.FLR_ID,'층') AS  REGION_NM_V2, '4' AS LVL , '17' AS SCALE, 25 AS VIEW_ODR, 'Y' AS USE_YN, 'NODE_END' AS COMMENT, B.CRET_DT AS REG_DATE
				FROM T_OBDNG_INFO_BAS A, T_OBDNG_FLR_INFO_BAS B, (
					SELECT B.OBDNG_ID AS REGION_CD, A.REGION_SUB_CD AS REGION_SUB_CD, B.OBDNG_NM AS REGION_NM, '3' AS LVL, '12' AS SCALE, 20 AS VIEW_ODR, 'Y' AS USE_YN, '' AS COMMENT
					FROM T_REGION_CD A, T_OBDNG_INFO_BAS B
					WHERE A.REGION_SUB_CD = B.RGN_CD
					  AND A.USE_YN = 'Y'
				) C
				WHERE A.OBDNG_ID = B.OBDNG_ID
				  AND A.RGN_CD = C.REGION_SUB_CD
				GROUP BY B.FLR_ID, A.OBDNG_ID, C.REGION_SUB_CD, B.CRET_DT
				ORDER BY REGION_SUB_CD, REGION_CD