SELECT  B.STAND_DT,
		B.TIME_CD
		 , COALESCE(A.USE_AMT_FA,0) AS USE_AMT_FA
		FROM (
			 SELECT METER_SN
					, STAND_DT
					, TIME_CD
					, SUM(USE_AMT_FA) AS USE_AMT_FA
			FROM T_MR_METER_BYTM_SUM A
			WHERE METER_SN IN ('000000000045')
			  AND STAND_DT BETWEEN '20131106' AND '20131106'
			GROUP BY METER_SN, STAND_DT, TIME_CD
			ORDER BY METER_SN, STAND_DT, TIME_CD
		) A RIGHT OUTER JOIN (
			SELECT to_char('20131106'::date - i,'yyyymmdd') as STAND_DT, TIME_CD
			FROM generate_series(0,(select '20131106'::date - '20131106'::date)) as t(i)
			INNER JOIN T_TIME_CD
			ON CD_TYPE='H01'
		 ) B
		ON A.STAND_DT = B.STAND_DT
		AND A.TIME_CD = B.TIME_CD



		SELECT METER_SN
				, STAND_DT
				, TIME_CD
				, SUM(USE_AMT_FA) AS USE_AMT_FA
		FROM T_MR_METER_BYTM_SUM
		WHERE METER_SN IN ('000000000045')
		  AND STAND_DT BETWEEN '20131106' AND '20131106'
		GROUP BY METER_SN, STAND_DT, TIME_CD
		ORDER BY METER_SN, STAND_DT, TIME_CD



		SELECT A.CBL, A.METER_SN, B.STAND_DT, B.TIME_CD, B.END_TM
			FROM (
				SELECT SUM(A.CBL) AS CBL, A.STAND_DT, C.TIME_CD, A.METER_SN
				FROM T_USER_CBL A, T_TIME_CD B, T_TIME_CD C
				WHERE A.TIME_CD = C.TIME_CD
				  AND B.REF2 = C.TIME_CD
				  AND B.CD_TYPE = 'M15'
				  AND C.CD_TYPE = 'H01'
				  AND A.STAND_DT = #{stand_dt}
				  AND METER_SN = #{meter_sn}
				GROUP BY A.CBL, C.TIME_CD, A.STAND_DT, A.METER_SN
				ORDER BY A.STAND_DT, C.TIME_CD
			) A RIGHT OUTER JOIN (
				SELECT  i, to_char(#{stand_dt}::date - i,'yyyymmdd') as STAND_DT, START_TM, END_TM, TIME_CD
				FROM generate_series(0,(select #{stand_dt}::date - #{stand_dt}::date)) as t(i) 
				INNER JOIN T_TIME_CD
				ON CD_TYPE='H01'
			) B
			ON A.STAND_DT = B.STAND_DT
			AND A.TIME_CD = B.TIME_CD


			SELECT *
			FROM T_OBDNG_BY_PURP_BYTM_SUM
			LIMIT 1