SELECT *
FROM T_OBDNG_IF_BAS

SELECT *
FROM T_OBDNG_BAS;

SELECT *
FROM T_OBDNG_INFO_BAS;

SELECT A.OBDNG_REP_ID, B.ISMART_ID, A.ASGN_RATE, A.IP_SET, B.LATIT, A.LNGIT,  B.RGN_CD, A.OBDNG_ID
FROM T_OBDNG_IF_BAS A, T_OBDNG_BAS B, T_OBDNG_INFO_BAS C
WHERE A.OBDNG_REP_ID = B.OBDNG_REP_ID
  AND C.OBDNG_REP_ID = B.OBDNG_REP_ID
  AND C.OBDNG_ID = 'A01-B0000004300'
ORDER BY A.OBDNG_REP_ID, B.ISMART_ID;



 SELECT A.OBDNG_ID, C.OBDNG_REP_ID, B.ISMART_ID, C.ASGN_RATE, C.IP_SET, B.LATIT, C.LNGIT, B.RGN_CD
 FROM T_OBDNG_INFO_BAS A, T_OBDNG_BAS B, T_OBDNG_IF_BAS C
 WHERE A.OBDNG_REP_ID = B.OBDNG_REP_ID
   AND A.OBDNG_ID = C.OBDNG_ID
   AND A.OBDNG_ID = 'A01-B0000004301'