SELECT *
FROM T_OBDNG_INFO_BAS



SELECT A.OBDNG_ID, C.OBDNG_REP_ID, B.ISMART_ID, C.ASGN_RATE, C.IP_SET, B.LATIT, C.LNGIT, B.RGN_CD 
FROM T_OBDNG_INFO_BAS A, T_OBDNG_BAS B, T_OBDNG_IF_BAS C 
WHERE A.OBDNG_REP_ID = B.OBDNG_REP_ID 
AND A.OBDNG_ID = C.OBDNG_ID 
AND c.OBDNG_ID = 'A02-B0000001207'

SELECT *
FROM T_OBDNG_INFO_BAS
WHERE OBDNG_ID = 'A02-B0000001207'

--A02-B0000001207


INSERT INTO T_OBDNG_INFO_BAS( OBDNG_ID, OBDNG_NM, TOWN_CD, GRS_VAL, OBDNG_REP_ID, ISMART_ID, ASGN_RATE, IP_SET, LATIT, LNGIT, RGN_CD, UPD_DT_IDX, CRET_DT ) 
VALUES ( 'A02-B0000001207' , '안산사옥(본동)' , '4127310100' , '10177.94' , null , null , null , null , null , null , null , TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS') , CURRENT_TIMESTAMP )

(String), (String), (String), (Float), null, null, null, null, null, null, null



SELECT C.OBDNG_REP_ID, B.ISMART_ID, C.ASGN_RATE, C.IP_SET, B.LATIT, C.LNGIT, B.RGN_CD, B.OBDNG_ADR, B.CHAGE_APLY_ELECT
FROM T_OBDNG_BAS B, T_OBDNG_IF_BAS C
WHERE B.OBDNG_REP_ID = C.OBDNG_REP_ID
AND C.OBDNG_ID = 'A08-B0000001461'

		   SELECT *
		   FROM T_OBDNG_BAS

		   SELECT COUNT(*)
		   FROM T_OBDNG_IF_BAS

SELECT ISMART_CNS_QNT
FROM T_OBDNG_ISMART_BYTM_SUM
LIMIT 1

SELECT *
FROM T_MR_METER
WHERE STAND_DT = '20131018'


SELECT coalesce(A.FREQUENCY, 0) AS FREQUENCY ,
       coalesce(A.VOLTAGE, 0) AS VOLTAGE ,
       coalesce(A.CURRENT, 0) AS CURRENT ,
       coalesce(A.POWER_FACTOR, 0) AS POWER_FACTOR,
       A.METER_SN
FROM T_MR_METER A
RIGHT OUTER JOIN
  (SELECT i,
          to_char('20131018'::date - i,'yyyymmdd') AS STAND_DT,
          START_TM,
          END_TM,
          TIME_CD
   FROM generate_series(0,
                          (SELECT '20131018'::date - '20131018'::date)) AS t(i)
   INNER JOIN T_TIME_CD ON CD_TYPE='H01'
   ORDER BY STAND_DT,
            START_TM) B ON B.STAND_DT = A.STAND_DT
AND B.TIME_CD = A.TIME_CD
AND A.METER_SN = ?



SELECT COUNT(*)
FROM T_MR_METER
WHERE STAND_DT = '20131018'