SELECT *
FROM T_OBDNG_INFO_TMP
LIMIT 100

SELECT *
FROM T_OBDNG_INSTN_INFO_BAS

SELECT *
FROM T_OBDNG_INFO_BAS_TMP

SELECT COUNT(*)
FROM T_OBDNG_INFO_BAS

SELECT COUNT(*)
FROM T_OBDNG_FLR_INFO_BAS

SELECT COUNT(*)
FROM T_OBDNG_INSTN_INFO_BAS


SELECT COUNT(*)
FROM T_OBDNG_INFO_BAS_TMP

SELECT COUNT(*)
FROM T_OBDNG_FLR_INFO_BAS_TMP

SELECT COUNT(*)
FROM T_OBDNG_INSTN_INFO_BAS_TMP

SELECT *
FROM T_OBDNG_INFO_BAS
WHERE OBDNG_ID = 'A08-B0000001752'
LIMIT 1

SELECT *
FROM T_OBDNG_FLR_INFO_BAS
WHERE OBDNG_ID = 'A08-B0000001752'
LIMIT 100

SELECT *
FROM T_OBDNG_INSTN_INFO_BAS
WHERE OBDNG_ID = 'A08-B0000001752'
ORDER BY OBDNG_ID, FLR_ID, OFCE_ID, INSTN_ID
LIMIT 100

-- DELETE FROM T_OBDNG_INSTN_INFO_BAS
-- COMMIT
