SELECT NAME, STAND_DT, STAND_TM, USE_AMT
FROM T_MR_FEEDER
WHERE STAND_DT = '20131120'
GROUP BY NAME, STAND_DT, STAND_TM, USE_AMT

SELECT *
FROM T_MR_FEEDER
WHERE STAND_DT = '20131120'
ORDER BY NAME, STAND_TM DESC


SELECT NAME, MAX(USE_AMT) 
FROM T_MR_FEEDER
WHERE STAND_DT = '20131120'
GROUP BY NAME, USE_AMT
ORDER BY NAME, USE_AMT DESC

SELECT COUNT(*)
FROM T_MR_FEEDER

SELECT NAME, MAX(STAND_TM) AS STAND_TM
FROM T_MR_FEEDER
WHERE 1=1
  AND STAND_DT = '20131120'
GROUP BY NAME

SELECT A.NAME, A.STAND_TM, A.STAND_DT, A.USE_AMT
FROM (
	SELECT NAME, STAND_TM, STAND_DT, USE_AMT
	FROM T_MR_FEEDER
	WHERE 1=1
	    AND STAND_DT = '20131120'
) A, (
	SELECT NAME, MAX(STAND_TM) AS STAND_TM
	FROM T_MR_FEEDER
	WHERE 1=1
	  AND STAND_DT = '20131120'
	GROUP BY NAME
)B
WHERE A.STAND_TM = B.STAND_TM
    AND A.NAME = B.NAME
ORDER BY A.NAME    
